### ISSUE TITLE
Error: Cannot access child value on Newtonsoft.Json.Linq.JValue.

### ISSUE THREAD

**Issue by 87ouo** [QingQiz/IcpcResolver.Net#12]
Something happened while I was exporting the example `Event-Feed.json` you have given in this project to the `loader`.
It warming me that `Error: Cannot access child value on Newtonsoft.Json.Linq.JValue.`
Here is the full warming message it gave me.

``` 
An application error occurred.
Please check whether your data is correct and repeat the action. lf thiserror occurs again there seems to be a more serious malfunction in theapplication, and you better close it.
Error: Cannot access child value on Newtonsoft.Json.Linq.JValue.
Do you want to continue?
(if you click Yes you will continue with your work, if you click No theapplication will close)
```
![屏幕截图 2021-05-19 103243](https://user-images.githubusercontent.com/13842409/118748338-3fc9f900-b88e-11eb-8244-733b68dc86c0.jpg)

Could you help me plz.
( I have no any idea with C# and WPF, sorry about that. )

**Comment by hktkqj** [comment]
> Something happened while I was exporting the example `Event-Feed.json` you have given in this project to the `loader`.
> It warming me that `Error: Cannot access child value on Newtonsoft.Json.Linq.JValue.`
> Here is the full warming message it gave me.
> 
> ```
> An application error occurred.
> Please check whether your data is correct and repeat the action. lf thiserror occurs again there seems to be a more serious malfunction in theapplication, and you better close it.
> Error: Cannot access child value on Newtonsoft.Json.Linq.JValue.
> Do you want to continue?
> (if you click Yes you will continue with your work, if you click No theapplication will close)
> ```
> 
> ![屏幕截图 2021-05-19 103243](https://user-images.githubusercontent.com/13842409/118748338-3fc9f900-b88e-11eb-8244-733b68dc86c0.jpg)
> 
> Could you help me plz.
> ( I have no any idea with C# and WPF, sorry about that. )

A typo writen by me in [src/IcpcResolver/Window/Validator.cs](Validator.cs) caused this exception, sorry......Fixed in the latest PR

**Comment by 87ouo** [comment]
Ok, thanks.
Looking forward to your new release.
ovo

**Comment by QingQiz** [comment]
fixed in new release
