### ISSUE TITLE
It seems that the UI has some problems.

### ISSUE THREAD

**Issue by 87ouo** [QingQiz/IcpcResolver.Net#14]
When the board is beginning to roll, at the bottom of the rolling board, the last one`s line is half-displaying, it misses some part!
![image](https://user-images.githubusercontent.com/13842409/118763029-c50ed700-b8a9-11eb-8700-dd8a02388617.png)

What's more, if I did not set the problem's [External ID] , the labels of the problems will be empty. Like this:
![image](https://user-images.githubusercontent.com/13842409/118763333-3ea6c500-b8aa-11eb-8ee9-a5c503715663.png)

HELP HELP PLZ.
Best wishes.

**Comment by 87ouo** [comment]
Also, I have a little suggestion: can the background keep rolling with the board when the board is rolling?

**Comment by QingQiz** [comment]
Adjust `Team Grid Height` and `Max Display Count` in `Animation Config` may help you solve the first issue.

> When the board is beginning to roll, at the bottom of the rolling board, the last one`s line is half-displaying, it misses some part!
> ![image](https://user-images.githubusercontent.com/13842409/118763029-c50ed700-b8a9-11eb-8700-dd8a02388617.png)
>

**Comment by hktkqj** [comment]
> What's more, if I did not set the problem's [External ID] , the labels of the problems will be empty. Like this:
> ![image](https://user-images.githubusercontent.com/13842409/118763333-3ea6c500-b8aa-11eb-8ee9-a5c503715663.png)

As for problem's labels, we only read `short_name` field in event feed as its label, see [defination of Problem entity](https://github.com/QingQiz/IcpcResolver.Net/blob/8d16859e83f5762dbebb203cc53a717a9ec8ae0e/src/IcpcResolver/Window/Validator.cs#L255), `external id` field is irrelevant to board display. We may add `external id` display fallback as an option.

**Comment by 87ouo** [comment]
> > What's more, if I did not set the problem's [External ID], the labels of the problems will be empty. Like this:
> > ![image](https://user-images.githubusercontent.com/13842409/118763333-3ea6c500-b8aa-11eb-8ee9-a5c503715663.png)
> 
> As for problem's labels, we only read `short_name` field in event feed as its label, see [defination of Problem entity](https://github.com/QingQiz/IcpcResolver.Net/blob/8d16859e83f5762dbebb203cc53a717a9ec8ae0e/src/IcpcResolver/Window/Validator.cs#L255), `external id` field is irrelevant to board display. We may add `external id` display fallback as an option.

Oh, HUGE SORRY! I missed up `external id` and `short_name`! As for now stage's usage, `short_name` is well enough, thank you! And best wishes to your dev team.
